<a href="https://colab.research.google.com/github/Tiepbn/Data-Aaalytics-with-python/blob/inClass/2012bai1InClass.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Bài Tập
---
Viết chương trình người dùng nhập vào 2 mảng 2 chiều có cùng kích thước (với điều kiện không có số 0) Thực hiện các phép toán cộng, trừ, nhân, chia các phần tử của 2 mảng đó.

**1**.Tính tổng các phần tử theo cột của mảng cuối cùng.

**2**.Tính tích các phần tử theo hàng của mảng cuối cùng.

In [6]:
a = input().split()
a = [float(i) for i in a]
print(type(a[0]))

1 2 3 4
<class 'float'>


In [12]:
from re import sub
import numpy as np

def nhap_mang_2_chieu(row,col):
  array = []
  for i in range(row):
    row_i = []
    for j in range(col):
      element = float(input(f"Nhập phần tử ở hàng {i+1}, cột {j+1}: "))
      row_i.append(element)
    array.append(row_i)
  return array

def addTwoArray(array1, array2):
  result_array = []
  for i in range(len(array1)):
    row_i = []
    for j in range(len(array1[0])):
      print()
      print(type(array1[i][j]))
      print(type(array2[i][j]))
      row_i.append(array1[i][j] + array2[i][j])
    result_array.append(row_i)
  return result_array

def subTwoArray(array1, array2):
  result_array = []
  for i in range(len(array1)):
    row_i = []
    for j in range(len(array1[0])):
      row_i.append(array1[i][j] - array2[i][j])
    result_array.append(row_i)
  return result_array

row = int(input("nhập số hàng: "))
col = int(input("nhập số cột: "))

array1 = nhap_mang_2_chieu(row, col)
array2 = nhap_mang_2_chieu(row,col)

print(addTwoArray(array1,array2))
print(subTwoArray(array1,array2))

nr1 = np.array(array1)
nr2 = np.array(array2)

print(np.add(nr1,nr2))
print(np.subtract(nr1,nr2))
print(np.multiply(nr1,nr2))
print(np.divide(nr1,nr2))

nhập số hàng: 2
nhập số cột: 2
Nhập phần tử ở hàng 1, cột 1: 1
Nhập phần tử ở hàng 1, cột 2: 2
Nhập phần tử ở hàng 2, cột 1: 3
Nhập phần tử ở hàng 2, cột 2: 4
Nhập phần tử ở hàng 1, cột 1: 5
Nhập phần tử ở hàng 1, cột 2: 6
Nhập phần tử ở hàng 2, cột 1: 7
Nhập phần tử ở hàng 2, cột 2: 8

<class 'float'>
<class 'float'>

<class 'float'>
<class 'float'>

<class 'float'>
<class 'float'>

<class 'float'>
<class 'float'>
[[6.0, 8.0], [10.0, 12.0]]
[[-4.0, -4.0], [-4.0, -4.0]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
