<a href="https://colab.research.google.com/github/Tiepbn/Data-Aaalytics-with-python/blob/main/BTw4_phan_tich_diem_thi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
## Gọi ra những thư viện cần thiết
import numpy as np
import pandas as pd

In [13]:
dataset = pd.read_excel("/content/Week4-data_06.xlsx")
print(dataset.head())

                 Tên  Mã số               Trường cấp 2  Nguyện vọng 1  \
0       QUÁCH KIM HÀ  60132             THCS Phú Cường              6   
1   PHẠM TRÚC PHƯƠNG  60421        THCS Trần Đại Nghĩa              6   
2     TRẦN KHẢ DOANH  60075    THCS-THPT Nguyễn Khuyến              6   
3  NGUYỄN MAI PHƯƠNG  60417        THCS Trần Đại Nghĩa              6   
4      TRẦN MINH THY  60558  THCS Nguyễn Thị Minh Khai              6   

   Nguyện vọng 2  Điểm cộng   Văn   Anh  Toán   Tổng  Xếp hạng  
0            2.0        3.0  9.00   8.9  8.75  29.65         1  
1            7.0        2.0  8.75   9.6  9.25  29.60         2  
2            7.0        2.0  8.25   9.6  9.25  29.10         3  
3            7.0        NaN  8.75  10.0  9.25  28.00         4  
4            2.0        2.0  8.25   9.7  8.00  27.95         5  


In [4]:
data = dataset.to_numpy()
print(data.shape)

(641, 11)


In [5]:
print(data[0])

['QUÁCH KIM HÀ' 60132 'THCS Phú Cường' 6 2.0 3.0 9.0 8.9 8.75 29.65 1]


In [7]:
print(data.dtype)

object


In [8]:
print(data[0].dtype)

object


In [9]:
np.nan_to_num([0.3, np.nan, 2.4])

array([0.3, 0. , 2.4])

In [14]:
data[:, 5] = np.nan_to_num(data[:, 5].astype(float))

print(data[-1])

['LƯU QUANG ĐÔ' 60108 'THCS Trịnh Hoài Đức' 6 30.0 0.0 5.5 2.4 3.75 11.65
 641]


In [11]:
## Đưa ra thông tin của bạn với mã số: 60457
## Đưa ra thông tin của bạn với tên là: Nguyễn Đình Nhân
## Đưa ra thông tin của các bạn từ mã số: 60004 đến  60200 (Bạn nào không có thì không cần đưa ra)


## Tính điểm thi trung bình cho từng bạn sinh viên
## Tính điểm thi trung bình theo từng môn cho toàn bộ sinh viên
## Đưa ra điểm thi trung bình cao nhất và thấp nhất cho toàn bộ 3 môn.
## Xếp danh sách dựa vào điểm trung bình của môn Toán + Anh, tìm bạn có vị trí 100


## Giả sử 1 trường lấy toàn bộ 300 sinh viên, dựa theo
## a) Điểm môn Toán từ cao xuống thấp
## b) Điểm tổng 3 môn và điểm cộng từ cao xuống thấp
## c) Điểm trung bình 3 môn từ cao xuống thấp
## Đưa ra danh sách những bạn sinh viên được chọn vào trường đó.


## So sánh 2 bạn sinh viên mã số: 60575 và 60602 dựa trên tổng điểm 3 môn (không tính điểm cộng)

##Đưa ra thông tin của bạn với mã số: 60457

In [17]:
print(data[0][1])

60132


In [20]:
print(np.where(data == 60457))

(array([100]), array([1]))


In [21]:
print(data[100])

['NGUYỄN LÊ PHƯƠNG TÂM' 60457 'THCS Phú Long' 6 7.0 2.0 7.0 9.4 6.25 24.65
 101]


## Đưa ra thông tin của bạn với tên là: Nguyễn Đình Nhân

In [22]:
## Đưa ra thông tin của bạn với tên là: Nguyễn Đình Nhân

In [23]:
print(np.where(data == "NGUYỄN ĐÌNH NHÂN"))

(array([106]), array([0]))


In [24]:
print(data[106])

['NGUYỄN ĐÌNH NHÂN' 60350 'THCS Nguyễn Văn Tiết' 6 7.0 2.0 6.0 8.6 8.0
 24.6 107]


In [28]:
data_id = data[:,1]
data_id[0:3]

array([60132, 60421, 60075], dtype=object)


## Đưa ra thông tin của các bạn từ mã số: 60004 đến  60200 (Bạn nào không có thì không cần đưa ra)

In [39]:
def print_from_to(a,b):
  t=a
  for i in range(b-a+1):
    index = np.where(data_id == a)
    print(data[index])
    a+=1
print_from_to(60004,60200)

[['NGÔ MỸ GIA AN' 60004 'THCS-THPT Nguyễn Khuyến' 6 2.0 2.0 7.5 9.3 8.75
  27.55 11]]
[['ĐỖ TRỌNG QUỐC AN' 60005 'THÍ SINH TỰ DO' 6 30.0 0.0 6.0 5.4 5.25 16.65
  599]]
[['TRẦN NGUYỄN KHÁNH AN' 60006 'THCS Thái Hòa' 6 13.0 1.0 6.5 8.2 6.25
  21.95 307]]
[['TRẦN MINH AN' 60007 'THCS-THPT Nguyễn Khuyến' 6 2.0 0.0 6.25 4.4 4.75
  15.4 621]]
[['NGUYỄN THỊ DÂN AN' 60008 'THCS Phú Long' 6 7.0 2.0 7.75 8.3 7.75 25.8
  45]]
[['NGUYỄN LÝ KHÁNH AN' 60009 'THCS Nguyễn Thị Minh Khai' 6 2.0 0.0 7.75
  8.3 8.0 24.05 140]]
[['NGUYỄN NGỌC QUỲNH ANH' 60010 'THCS Trịnh Hoài Đức' 6 8.0 2.0 7.5 9.8
  6.75 26.05 41]]
[['PHAN BÙI KIỀU ANH' 60011 'THCS Nguyễn Thái Bình' 6 29.0 0.0 7.0 7.9
  7.75 22.65 252]]
[['NGUYỄN QUỐC ANH' 60012 'THCS Nguyễn Trung Trực' 6 8.0 0.0 7.25 5.6
  7.25 20.1 456]]
[['NGÔ ĐAN ANH' 60013 'THCS Thuận Giao' 6 8.0 0.0 8.0 7.7 7.25 22.95 228]]
[['TRẦN THỊ PHƯƠNG ANH' 60014 'THCS Bình Chuẩn' 6 30.0 0.0 7.5 6.5 7.25
  21.25 368]]
[['HOÀNG QUANG ANH' 60015 'THCS Phú Hòa' 6 2.0 0.0 6.25 7.